version: "3"

services:
  web:
    container_name: harebare_web
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: php -S 0.0.0.0:8080 -t public
    environment:
      DB_HOST: harebare_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: harebare_dev
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  db:
    container_name: harebare_db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password

    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db:/db
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "harebare_dev"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"

volumes:
  mysql-data:
    driver: local
